export const agroCategories = [
  "Accesorios",
  "Acoplados",
  "Agricultura de precisión",
  "Cabezales",
  "Cabinas",
  "Camiones",
  "Casillas",
  "Clasificadoras",
  "Cosechadoras",
  "Desmalezadoras",
  "Discos",
  "Drones",
  "Elevadores de granos",
  "Embolsadoras",
  "Energía solar",
  "Extractoras de cereales",
  "Fertilizadoras",
  "Grúas hidráulicas",
  "Grupos electrógenos",
  "Infraestructura",
  "Labranza",
  "Maquinaria vial",
  "Mixers",
  "Moledoras",
  "Palas",
  "Picadoras",
  "Pulverizadoras",
  "Rastrillos",
  "Rolos",
  "Rotoenfardadoras",
  "Segadoras",
  "Sembradoras",
  "Semirremolques",
  "Tanques",
  "Tolvas",
  "Tractores",
  "Transporte de rollos",
  "Vehículos",
  "Otros",
].map((name) => ({
  name,
  slug: name
    .normalize("NFD")
    .replace(/[\u0300-\u036f]/g, "")
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/(^-|-$)/g, ""),
}));
