import type { Category, Listing } from "@/types/domain";

export const categories: Category[] = [
  { id: "cat-autos", name: "Autos", slug: "autos", description: "Unidades urbanas y familiares.", icon: "car" },
  { id: "cat-pickups", name: "Pickups", slug: "pickups", description: "Trabajo, campo y ruta.", icon: "truck" },
  { id: "cat-utilitarios", name: "Utilitarios", slug: "utilitarios", description: "Logística liviana y reparto.", icon: "package" },
  { id: "cat-camiones", name: "Camiones livianos", slug: "camiones-livianos", description: "Carga y trabajo.", icon: "truck" },
  { id: "cat-agro", name: "Agro", slug: "agro", description: "Soluciones productivas.", icon: "sprout" },
  { id: "cat-maquinaria", name: "Maquinaria agrícola", slug: "maquinaria-agricola", description: "Equipos para campaña.", icon: "tractor" },
  { id: "cat-implementos", name: "Implementos", slug: "implementos", description: "Herramientas e implementos.", icon: "wrench" },
];

export const demoListings: Listing[] = [
  {
    id: "11111111-1111-4111-8111-111111111111",
    title: "Toyota Hilux SRX 4x4 AT",
    slug: "toyota-hilux-srx-4x4-at-2022",
    category_id: "cat-pickups",
    category: categories[1],
    brand_id: "brand-toyota",
    brand: { id: "brand-toyota", name: "Toyota", slug: "toyota" },
    model_id: null,
    year: 2022,
    price: 43500,
    currency: "USD",
    price_usd: 43500,
    price_ars: 52000000,
    location_city: "Venado Tuerto",
    location_province: "Santa Fe",
    description: "Pickup verificada, lista para transferencia. Service al día, neumáticos en buen estado y equipamiento completo.",
    condition: "used",
    mileage: 74000,
    fuel_type: "Diesel",
    transmission: "Automática",
    traction: "4x4",
    engine: "2.8",
    hours_used: null,
    accepts_trade_in: true,
    financing_available: true,
    is_verified: true,
    is_select: true,
    is_featured: true,
    status: "published",
    seller_type: "agency",
    organization_id: null,
    owner_profile_id: null,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    listing_images: [
      {
        id: "img-1",
        listing_id: "11111111-1111-4111-8111-111111111111",
        url: "https://loremflickr.com/1200/900/toyota,hilux,pickup",
        alt: "Toyota Hilux pickup en exterior",
        sort_order: 0,
      },
    ],
  },
  {
    id: "22222222-2222-4222-8222-222222222222",
    title: "Volkswagen Amarok Comfortline",
    slug: "volkswagen-amarok-comfortline-2021",
    category_id: "cat-pickups",
    category: categories[1],
    brand_id: "brand-volkswagen",
    brand: { id: "brand-volkswagen", name: "Volkswagen", slug: "volkswagen" },
    model_id: null,
    year: 2021,
    price: 36500,
    currency: "USD",
    price_usd: 36500,
    price_ars: 43800000,
    location_city: "Firmat",
    location_province: "Santa Fe",
    description: "Unidad de uso particular, interior cuidado, apta financiación y permuta menor.",
    condition: "used",
    mileage: 91000,
    fuel_type: "Diesel",
    transmission: "Manual",
    traction: "4x2",
    engine: "2.0",
    hours_used: null,
    accepts_trade_in: true,
    financing_available: true,
    is_verified: true,
    is_select: false,
    is_featured: true,
    status: "published",
    seller_type: "agency",
    organization_id: null,
    owner_profile_id: null,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    listing_images: [
      {
        id: "img-2",
        listing_id: "22222222-2222-4222-8222-222222222222",
        url: "https://loremflickr.com/1200/900/volkswagen,amarok,pickup",
        alt: "Volkswagen Amarok pickup",
        sort_order: 0,
      },
    ],
  },
  {
    id: "33333333-3333-4333-8333-333333333333",
    title: "Tractor John Deere 5075E",
    slug: "tractor-john-deere-5075e-2019",
    category_id: "cat-maquinaria",
    category: categories[5],
    brand_id: "brand-john-deere",
    brand: { id: "brand-john-deere", name: "John Deere", slug: "john-deere" },
    model_id: null,
    year: 2019,
    price: 52000,
    currency: "USD",
    price_usd: 52000,
    price_ars: 62400000,
    location_city: "Rufino",
    location_province: "Santa Fe",
    description: "Tractor con 1800 horas, cabina, hidráulicos revisados y disponibilidad inmediata para campaña.",
    condition: "used",
    mileage: null,
    fuel_type: "Diesel",
    transmission: "Manual",
    traction: "4x4",
    engine: "75 HP",
    hours_used: 1800,
    accepts_trade_in: false,
    financing_available: true,
    is_verified: true,
    is_select: true,
    is_featured: true,
    status: "published",
    seller_type: "internal",
    organization_id: null,
    owner_profile_id: null,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    listing_images: [
      {
        id: "img-3",
        listing_id: "33333333-3333-4333-8333-333333333333",
        url: "https://loremflickr.com/1200/900/john-deere,tractor",
        alt: "Tractor John Deere trabajando",
        sort_order: 0,
      },
    ],
  },
];
