insert into public.categories (name, slug, description, icon, sort_order) values
('Accesorios', 'accesorios', 'Categoría de línea agro.', 'tractor', 20),
('Acoplados', 'acoplados', 'Categoría de línea agro.', 'tractor', 21),
('Agricultura de precisión', 'agricultura-de-precision', 'Categoría de línea agro.', 'tractor', 22),
('Cabezales', 'cabezales', 'Categoría de línea agro.', 'tractor', 23),
('Cabinas', 'cabinas', 'Categoría de línea agro.', 'tractor', 24),
('Camiones', 'camiones', 'Categoría de línea agro.', 'truck', 25),
('Casillas', 'casillas', 'Categoría de línea agro.', 'tractor', 26),
('Clasificadoras', 'clasificadoras', 'Categoría de línea agro.', 'tractor', 27),
('Cosechadoras', 'cosechadoras', 'Categoría de línea agro.', 'tractor', 28),
('Desmalezadoras', 'desmalezadoras', 'Categoría de línea agro.', 'tractor', 29),
('Discos', 'discos', 'Categoría de línea agro.', 'tractor', 30),
('Drones', 'drones', 'Categoría de línea agro.', 'tractor', 31),
('Elevadores de granos', 'elevadores-de-granos', 'Categoría de línea agro.', 'tractor', 32),
('Embolsadoras', 'embolsadoras', 'Categoría de línea agro.', 'tractor', 33),
('Energía solar', 'energia-solar', 'Categoría de línea agro.', 'tractor', 34),
('Extractoras de cereales', 'extractoras-de-cereales', 'Categoría de línea agro.', 'tractor', 35),
('Fertilizadoras', 'fertilizadoras', 'Categoría de línea agro.', 'tractor', 36),
('Grúas hidráulicas', 'gruas-hidraulicas', 'Categoría de línea agro.', 'tractor', 37),
('Grupos electrógenos', 'grupos-electrogenos', 'Categoría de línea agro.', 'tractor', 38),
('Infraestructura', 'infraestructura', 'Categoría de línea agro.', 'tractor', 39),
('Labranza', 'labranza', 'Categoría de línea agro.', 'tractor', 40),
('Maquinaria vial', 'maquinaria-vial', 'Categoría de línea agro.', 'tractor', 41),
('Mixers', 'mixers', 'Categoría de línea agro.', 'tractor', 42),
('Moledoras', 'moledoras', 'Categoría de línea agro.', 'tractor', 43),
('Palas', 'palas', 'Categoría de línea agro.', 'tractor', 44),
('Picadoras', 'picadoras', 'Categoría de línea agro.', 'tractor', 45),
('Pulverizadoras', 'pulverizadoras', 'Categoría de línea agro.', 'tractor', 46),
('Rastrillos', 'rastrillos', 'Categoría de línea agro.', 'tractor', 47),
('Rolos', 'rolos', 'Categoría de línea agro.', 'tractor', 48),
('Rotoenfardadoras', 'rotoenfardadoras', 'Categoría de línea agro.', 'tractor', 49),
('Segadoras', 'segadoras', 'Categoría de línea agro.', 'tractor', 50),
('Sembradoras', 'sembradoras', 'Categoría de línea agro.', 'tractor', 51),
('Semirremolques', 'semirremolques', 'Categoría de línea agro.', 'tractor', 52),
('Tanques', 'tanques', 'Categoría de línea agro.', 'tractor', 53),
('Tolvas', 'tolvas', 'Categoría de línea agro.', 'tractor', 54),
('Tractores', 'tractores', 'Categoría de línea agro.', 'tractor', 55),
('Transporte de rollos', 'transporte-de-rollos', 'Categoría de línea agro.', 'tractor', 56),
('Vehículos', 'vehiculos', 'Categoría de línea agro.', 'truck', 57),
('Otros', 'otros', 'Categoría de línea agro.', 'tractor', 58)
on conflict (slug) do update set
  name = excluded.name,
  description = excluded.description,
  icon = excluded.icon,
  sort_order = excluded.sort_order,
  is_active = true;
